name: Audit Documentation

# 🚨 CHANGE 1: Run ONLY on Pull Requests (so we always have a PR to comment on)
on: [pull_request]

jobs:
  check-docs:
    runs-on: ubuntu-latest
    
    # 🚨 CHANGE 2: Grant permission to write comments
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run DockDesk
        uses: srivatsa-source/dockdesk@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          code_file: 'auth.js'
          doc_file: 'docs.md'